---
- hosts: aws_ec2
  become: yes
 
  handlers:
  - name: Reload Nginx
    service:
      name: nginx
      state: reloaded

  - name: Start and enable services
    systemd:
      name: '{{ item }}'
      state: started 
      enabled: yes 
    with_items:
      - nginx
      - crond
    notify: "configure ssl"


### SSL part


  - name: Apply Nginx template without SSL
    template:
      src: files/nginx.conf.j2
      dest: /etc/nginx/conf.d/{{ domain_name }}.conf
    listen: "configure ssl"
    notify: Reload Nginx

  - name: Create ssl directory 
    file:
      path: /etc/nginx/ssl
      state: directory
    listen: "configure ssl"

  - name: Download and install acme.sh
    shell: "curl https://get.acme.sh | sh -s email=root@{{ domain_name }}"
    listen: "configure ssl"

  - name: Get SSL certificate
    shell: "~/.acme.sh/acme.sh --issue --nginx -d {{ domain_name }}" #--server  letsencrypt"
    listen: "configure ssl"

  - name: Install certificate and reload nginx
    shell: |
      ~/.acme.sh/acme.sh --install-cert -d {{ domain_name }} \
      --key-file       /etc/nginx/ssl/key.pem  \
      --fullchain-file /etc/nginx/ssl/cert.crt \
      --reloadcmd     "service nginx force-reload"
    listen: "configure ssl"

  - name: Apply Nginx template with SSL
    template:
      src: files/nginx-ssl.conf.j2
      dest: /etc/nginx/conf.d/{{ domain_name }}.conf
    notify: Reload Nginx
    listen: "configure ssl"

  - name: Remove files and directories
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html
    listen: "configure ssl"



  tasks:

  - name: Install required packages
    ansible.builtin.dnf:
      name:
        - git
        - nginx
        - cronie
      state: present 
    notify: Start and enable services


  - name: Force all notified handlers to run at this point, not waiting for normal sync points
    ansible.builtin.meta: flush_handlers

  - name: Clone repository
    ansible.builtin.git:
      repo: "{{ repository_name }}"
      dest: /usr/share/nginx/html
      clone: yes
      update: yes

    